### ISSUE TITLE
Generator to support `additionalProperties`

### ISSUE THREAD

**Issue by threez** [pace/bricks#61]
### Problem

additionalProperties are not handled at the moment

### Proposed solution

```yaml
type: object
additionalProperties:
  type: string
```
Instead generate `map[string]string`.

```yaml
type: object
additionalProperties:
  type: integer
```
Instead generate `map[string]int`.

```yaml
type: object
additionalProperties: true
```

Instead generate `map[string]interface{}`.

In case properties are defined, a warning is displayed, that these are ignored, and only the map is generated.
