### ISSUE TITLE
Query params don't support string values that contain spaces

### ISSUE THREAD

**Issue by agandrabur** [pace/bricks#87]
When creating an OpenAPIv3 specs that has and endpoint with query params, it's not possible to pass a string that contains spaces

```yaml
...
paths:
  /api/test:
    get:
      operationId: testOperation
      summary: Test
      parameters:
        - in: query
          name: name
          schema:
            type: string
...
```
When calling the API with `curl -X GET "http://localhost:3030/api/test?name=test%20string -H "accept: application/vnd.api+json"`
the value in the handler function will be `r.ParamName="test"`

The issue seems to originate here: https://github.com/pace/bricks/blob/master/http/jsonapi/runtime/parameters.go#L93
